# YML is a text document formatted by YAML, a human-readable format used for data serialization.
# YAML is independent of programming languages and thus compatible with most of the languages.
# YML is commonly used to store metadata, versions, settings, and configuration within a project.